# Generated by Django 2.1.4 on 2019-02-20 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_extruder_waste',
            name='report_date',
            field=models.DateField(default=datetime.date(2019, 2, 20)),
        ),
        migrations.AlterField(
            model_name='manger',
            name='position',
            field=models.CharField(choices=[('coating', 'coating'), ('cutting', 'cutting'), ('looms', 'looms'), ('extruder', 'extruder'), ('sales', 'sales'), ('quality', 'quality'), ('printing', 'printing'), ('Production_manager', 'Production_manager'), ('follower', 'follower'), ('packing', 'packing'), ('normal', 'normal')], max_length=18),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('coating', 'coating'), ('cutting', 'cutting'), ('looms', 'looms'), ('extruder', 'extruder'), ('sales', 'sales'), ('quality', 'quality'), ('printing', 'printing'), ('Production_manager', 'Production_manager'), ('follower', 'follower'), ('packing', 'packing'), ('normal', 'normal')], max_length=18),
        ),
    ]
