# Generated by Django 2.1.4 on 2019-02-21 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0002_auto_20190220_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_extruder_waste',
            name='report_date',
            field=models.DateField(default=datetime.date(2019, 2, 21)),
        ),
    ]
