# Generated by Django 2.1.4 on 2019-03-02 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0003_auto_20190221_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_extruder_waste',
            name='report_date',
            field=models.DateField(default=datetime.date(2019, 3, 2)),
        ),
    ]
