# Generated by Django 2.1.4 on 2019-03-11 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0005_auto_20190302_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productio_order_test',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='productio_order',
            name='manager_agreement',
        ),
        migrations.RemoveField(
            model_name='productio_order_test2',
            name='manager_agreement',
        ),
        migrations.AddField(
            model_name='order_item',
            name='batch_depth',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order_item',
            name='batch_height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order_item',
            name='peice_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productio_order',
            name='isAdstar',
            field=models.CharField(choices=[('نعم', 'نعم'), ('لا', 'لا')], default='لا', max_length=10),
        ),
        migrations.AddField(
            model_name='productio_order',
            name='payment_time_tolerance',
            field=models.CharField(default='لا يوجد', max_length=1000),
        ),
        migrations.AddField(
            model_name='productio_order_test2',
            name='isAdstar',
            field=models.CharField(choices=[('نعم', 'نعم'), ('لا', 'لا')], default='لا', max_length=10),
        ),
        migrations.AddField(
            model_name='productio_order_test2',
            name='payment_time_tolerance',
            field=models.CharField(default='لا يوجد', max_length=1000),
        ),
        migrations.AddField(
            model_name='productio_order_test2',
            name='sales_manager_agreement',
            field=models.CharField(choices=[('نعم', 'نعم'), ('لا', 'لا')], default='لا', max_length=10),
        ),
        migrations.AlterField(
            model_name='daily_extruder_waste',
            name='report_date',
            field=models.DateField(default=datetime.date(2019, 3, 11)),
        ),
        migrations.AlterField(
            model_name='productio_order',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productio_order',
            name='production_manager_agreement',
            field=models.CharField(choices=[('نعم', 'نعم'), ('لا', 'لا')], default='لا', max_length=10),
        ),
        migrations.AlterField(
            model_name='productio_order',
            name='sales_manager_agreement',
            field=models.CharField(choices=[('نعم', 'نعم'), ('لا', 'لا')], default='لا', max_length=10),
        ),
        migrations.AlterField(
            model_name='productio_order_test2',
            name='production_manager_agreement',
            field=models.CharField(choices=[('نعم', 'نعم'), ('لا', 'لا')], default='لا', max_length=10),
        ),
        migrations.DeleteModel(
            name='Productio_order_test',
        ),
    ]
