# Generated by Django 2.1.4 on 2019-03-12 19:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0006_auto_20190311_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adstar_item',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='coating_daily_report',
            name='shift_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='howdy.coating_shift'),
        ),
        migrations.AlterField(
            model_name='daily_extruder_waste',
            name='report_date',
            field=models.DateField(default=datetime.date(2019, 3, 12)),
        ),
        migrations.DeleteModel(
            name='AdStar_Item',
        ),
    ]
