# Generated by Django 2.1.4 on 2019-03-13 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0007_auto_20190312_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad_daily_report_two',
            name='warehouser',
        ),
        migrations.RemoveField(
            model_name='ad_daily_report_two',
            name='waste_amount',
        ),
        migrations.AddField(
            model_name='ad_daily_report_two',
            name='coating_waste',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='ad_daily_report_two',
            name='cutting_waste',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='ad_daily_report_two',
            name='printing_waste',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='ad_daily_report_two',
            name='weaving_waste',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='daily_extruder_waste',
            name='report_date',
            field=models.DateField(default=datetime.date(2019, 3, 13)),
        ),
    ]
