# Generated by Django 2.1.4 on 2019-03-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0008_auto_20190313_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad_daily_report_two',
            name='production_amount',
        ),
        migrations.AddField(
            model_name='ad_daily_report_one',
            name='production_amount',
            field=models.FloatField(default=0),
        ),
    ]
