# Generated by Django 2.1.4 on 2019-03-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0009_auto_20190313_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad_daily_report_two',
            name='id',
        ),
        migrations.AddField(
            model_name='ad_daily_report_two',
            name='report_id_two',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
