# Generated by Django 2.1.4 on 2019-03-13 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0011_auto_20190313_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='AD_daily_report_two',
            fields=[
                ('report_id_two', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('packages', models.IntegerField(default=0)),
                ('printing_waste', models.FloatField(default=None)),
                ('cutting_waste', models.FloatField(default=None)),
                ('coating_waste', models.FloatField(default=None)),
                ('weaving_waste', models.FloatField(default=None)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howdy.Productio_order')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howdy.AD_daily_report_one')),
            ],
        ),
    ]
