# Generated by Django 2.1.4 on 2019-03-15 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0014_auto_20190315_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='roll_final_waste',
            fields=[
                ('roll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='howdy.Roll_Identifier')),
                ('cutting_waste', models.IntegerField()),
                ('printing_waste', models.IntegerField()),
                ('coating_waste', models.IntegerField()),
                ('weaving_waste', models.IntegerField()),
            ],
        ),
    ]
