# Generated by Django 2.1.4 on 2019-03-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0015_roll_final_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll_final_waste',
            name='shift_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='howdy.cutting_shift'),
        ),
    ]
